[package]
name = "editorconfig_ini"
version = "0.1.0"
authors = ["Jed Mao <jedmao@outlook.com>"]
keywords = ["editorconfig", "ini", "parser", "ast"]
categories = ["config", "parser-implementations", "wasm"]
edition = "2018"
repository = "https://github.com/editorconfi/editorconfig-ini-rust"
documentation = "https://docs.rs/editorconfig_ini"
license = "MIT"
publish = false

[dependencies]
clap = "2.33.0"
pest = "2.1.2"
pest_derive = "2.1.0"
